# Generated by Django 4.2.6 on 2023-10-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='produto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
